<?php

class LoanquestionsTableSeeder extends Seeder {

	public function run()
	{
		Loanquestions::create([
			'loan_id' 	=> 	1,
			'amount_requested' => 75000,
			'plant_own'		=>	1,
			'harvest_own'	=>	1,
			'equip_obligations'	=>	1,
			'other_cash'	=>	1,
			'fsa_good'		=>	1,
			'fci_good'		=>	1,
			'premiums_past'	=>	1,
			'legal_defendant'	=>	0,
			'judgements'		=>	0,
			'bankruptcy'	=>	0,
			'liens'			=>	0,
			'fsa_direct_pay'	=>	0,
			'future_liabilities'	=>	1,
			'credit_3p_available'	=>	0,
			'income_percent'		=>	100,
			'distributor'		=>	'JSI',
			'agency'			=>	'State Farm of Monroe',
			'pesticide_number'	=>	'2T23765',
			'credit_score'	=>	730,
			'cpa_financials'	=>	1,
			'affiliated_entities'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
			'farm_supplier_creditors'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.'
		]);

		Loanquestions::create([
			'loan_id' 	=> 	2,
			'amount_requested' => 35000,
      'plant_own'		=>	0,
      'plant_own_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'harvest_own'	=>	0,
      'harvest_own_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'equip_obligations'	=>	0,
      'equip_obligations_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'other_cash'	=>	0,
      'other_cash_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'fsa_good'		=>	0,
      'fsa_good_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'fci_good'		=>	0,
      'fci_good_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'premiums_past'	=>	1,
      'premiums_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'legal_defendant'	=>	1,
      'defendant_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'judgements'		=>	0,
      'judgement_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'bankruptcy'	=>	0,
      'bankruptcy_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'liens'			=>	1,
      'liens_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'fsa_direct_pay'	=>	1,
      'fsa_direct_pay_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'future_liabilities'	=>	1,
      'credit_3p_available'	=>	1,
      'credit_3p_details'		=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'income_percent'		=>	90,
      'income_distribution_details'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'distributor'		=>	'JSI',
      'agency'			=>	'',
      'pesticide_number'	=>	'2T23765',
      'credit_score'	=>	730,
      'cpa_financials'	=>	1,
      'affiliated_entities'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'farm_supplier_creditors'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.'
		]);

		Loanquestions::create([
			'loan_id' 	=> 	3,
			'amount_requested' => 100000,
			'plant_own'		=>	1,
			'harvest_own'	=>	1,
			'equip_obligations'	=>	1,
			'other_cash'	=>	0,
			'fsa_good'		=>	1,
			'fci_good'		=>	1,
			'premiums_past'	=>	0,
			'legal_defendant'	=>	0,
			'judgements'		=>	0,
			'bankruptcy'	=>	0,
			'liens'			=>	0,
			'fsa_direct_pay'	=>	0,
			'future_liabilities'	=>	0,
			'credit_3p_available'	=>	0,
			'income_percent'		=>	100,
			'distributor'		=>	'JSI',
			'agency'			=>	'',
			'pesticide_number'	=>	'2T23765',
			'credit_score'	=>	760,
			'cpa_financials'	=>	1,
			'affiliated_entities'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
			'farm_supplier_creditors'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.'
		]);

		Loanquestions::create([
			'loan_id' 	=> 	4,
			'amount_requested' => 750000,
			'plant_own'		=>	1,
			'harvest_own'	=>	1,
			'equip_obligations'	=>	1,
			'other_cash'	=>	0,
			'fsa_good'		=>	1,
			'fci_good'		=>	1,
			'premiums_past'	=>	0,
			'legal_defendant'	=>	0,
			'judgements'		=>	0,
			'bankruptcy'	=>	0,
			'liens'			=>	0,
			'fsa_direct_pay'	=>	0,
			'future_liabilities'	=>	0,
			'credit_3p_available'	=>	0,
			'income_percent'		=>	100,
			'distributor'		=>	'JSI',
			'agency'			=>	'',
			'pesticide_number'	=>	'2T23765',
			'credit_score'	=>	760,
			'cpa_financials'	=>	1,
			'affiliated_entities'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
			'farm_supplier_creditors'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.'
		]);

		Loanquestions::create([
			'loan_id' 	=> 	5,
			'amount_requested' => 1000000,
			'plant_own'		=>	1,
			'harvest_own'	=>	1,
			'equip_obligations'	=>	1,
			'other_cash'	=>	0,
			'fsa_good'		=>	1,
			'fci_good'		=>	1,
			'premiums_past'	=>	0,
			'legal_defendant'	=>	0,
			'judgements'		=>	0,
			'bankruptcy'	=>	0,
			'liens'			=>	0,
			'fsa_direct_pay'	=>	0,
			'future_liabilities'	=>	0,
			'credit_3p_available'	=>	0,
			'income_percent'		=>	100,
			'distributor'		=>	'JSI',
			'agency'			=>	'',
			'pesticide_number'	=>	'2T23765',
			'credit_score'	=>	760,
			'cpa_financials'	=>	1,
			'affiliated_entities'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
			'farm_supplier_creditors'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.'
		]);

    Loanquestions::create([
      'loan_id' 	=> 	6,
      'amount_requested' => 75000,
      'plant_own'		=>	1,
      'harvest_own'	=>	1,
      'equip_obligations'	=>	1,
      'other_cash'	=>	1,
      'fsa_good'		=>	1,
      'fci_good'		=>	1,
      'premiums_past'	=>	1,
      'legal_defendant'	=>	0,
      'judgements'		=>	0,
      'bankruptcy'	=>	0,
      'liens'			=>	0,
      'fsa_direct_pay'	=>	0,
      'future_liabilities'	=>	1,
      'credit_3p_available'	=>	0,
      'income_percent'		=>	100,
      'distributor'		=>	'JSI',
      'agency'			=>	'State Farm of Monroe',
      'pesticide_number'	=>	'2T23765',
      'credit_score'	=>	730,
      'cpa_financials'	=>	1,
      'affiliated_entities'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'farm_supplier_creditors'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.'
    ]);

    Loanquestions::create([
      'loan_id' 	=> 	7,
      'amount_requested' => 75000,
      'plant_own'		=>	1,
      'harvest_own'	=>	1,
      'equip_obligations'	=>	1,
      'other_cash'	=>	1,
      'fsa_good'		=>	1,
      'fci_good'		=>	1,
      'premiums_past'	=>	1,
      'legal_defendant'	=>	0,
      'judgements'		=>	0,
      'bankruptcy'	=>	0,
      'liens'			=>	0,
      'fsa_direct_pay'	=>	0,
      'future_liabilities'	=>	1,
      'credit_3p_available'	=>	0,
      'income_percent'		=>	100,
      'distributor'		=>	'JSI',
      'agency'			=>	'State Farm of Monroe',
      'pesticide_number'	=>	'2T23765',
      'credit_score'	=>	730,
      'cpa_financials'	=>	1,
      'affiliated_entities'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.',
      'farm_supplier_creditors'	=>	'Rutrum mi libero hymenaeos dolor posuere montes tristique litora cubilia.'
    ]);
	}
}