<?php namespace Acme\Transformers;

class LoanfinancialsTransformer extends Transformer{

	public function transform($arr)
	{
		//return $arr;
		return [
			'id' => (integer) $arr['id'],
			'loan_id' => (integer) $arr['loan_id'],
			'cpa_financials' => (boolean) $arr['cpa_financials'],
			'bankruptcy' => (boolean) $arr['bankruptcy'],
			'judgements' => (boolean) $arr['judgements'],
			'credit_score' => (double) $arr['credit_score'],
			'experience' => (double) $arr['experience'],
			'grade' => $arr['grade'],
			'amount_requested' => (double) $arr['amount_requested'],
			'collateral_equipment' => (double) $arr['collateral_equipment'],
			'collateral_realestate' => (double) $arr['collateral_realestate'],
			'total_acres' => (double) $arr['total_acres'],
			'int_percent_arm' => (double) $arr['int_percent_arm'],
			'int_arm' => (double) $arr['int_arm'],
			'int_dist' => (double) $arr['int_dist'],
			'int_other' => (double) $arr['int_other'],
			'interest' => (double) $arr['interest'],
			'int_percent_dist' => (double) $arr['int_percent_dist'],
			'int_percent_other' => (double) $arr['int_percent_other'],
			'fee_processing_percent' => (double) $arr['fee_processing'],
			'fee_processing_onTotal' => (boolean) $arr['fee_processing_onTotal'],
			'proc_fee' => (double) $arr['proc_fee'],
			'proc_fee_arm_only' => (double) $arr['proc_fee_arm_only'],
			'fee_service_percent' => (double) $arr['fee_service'],
			'fee_service_onTotal' => (boolean) $arr['fee_service_onTotal'],
			'srvc_fee' => (double) $arr['srvc_fee'],
			'srvc_fee_arm_only' => (double) $arr['srvc_fee_arm_only'],
			'total_fee_percent' => (double) $arr['total_fee_percent'],
			'fee_total' => (double) $arr['fee_total'],
			'total_fsa_payment' => (double) $arr['total_fsa_payment'],
			'total_claims' => (double) $arr['total_claims'],
			'total_revenue' => (double) $arr['total_revenue'],
			'total_balance' => (double) $arr['total_balance'],
			'remaining_balance' => (double) $arr['remaining_balance'],
			'balance_paid' => (double) $arr['balance_paid'],
			'cash_flow' => (double) $arr['cash_flow'],
			'risk' => (double) $arr['risk'],
			'risk_adj' => (double) $arr['risk_adj'],
			'year_1_revenue' => (double) $arr['year_1_revenue'],
			'year_1_expenses' => (double) $arr['year_1_expenses'],
			'year_2_revenue' => (double) $arr['year_2_revenue'],
			'year_2_expenses' => (double) $arr['year_2_expenses'],
			'year_3_revenue' => (double) $arr['year_3_revenue'],
			'year_3_expenses' => (double) $arr['year_3_expenses'],
			'current_assets' => (double) $arr['current_assets'],
			'current_assets_factor' => (double) $arr['current_assets_factor'],
			'current_assets_liability' => (double) $arr['current_assets_liability'],
			'intermediate_assets' => (double) $arr['intermediate_assets'],
			'intermediate_assets_factor' => (double) $arr['intermediate_assets_factor'],
			'intermediate_assets_liability' => (double) $arr['intermediate_assets_liability'],
			'fixed_assets' => (double) $arr['fixed_assets'],
			'fixed_assets_factor' => (double) $arr['fixed_assets_factor'],
			'fixed_assets_liability' => (double) $arr['fixed_assets_liability'],
			'guaranty' => (double) $arr['guaranty'],
			'debt2asset_ratio' => (double) $arr['debt2asset_ratio'],
			'debt2asset_ratio_adj' => (double) $arr['debt2asset_ratio_adj'],
			'ratio_current' => (double) $arr['ratio_current'],
			'ratio_current_adj' => (double) $arr['ratio_current_adj'],
			'capWork' => (double) $arr['capWork'],
			'capWork_adj' => (double) $arr['capWork_adj'],
			'capBorrow' => (double) $arr['capBorrow'],
			'capBorrow_adj' => (double) $arr['capBorrow_adj'],
			'prod' => (double) $arr['prod'],
			'adj_prod' => (double) $arr['adj_prod'],
			'disc_prod' => (double) $arr['disc_prod'],
			'disc_prod_percent' => (double) $arr['disc_prod_percent'],
			'non_rp_percent' => (double) $arr['non_rp_percent'],
			'disc_adj_prod' => (double) $arr['disc_adj_prod'],
			'ins_disc_prod' => (double) $arr['ins_disc_prod'],
			'disc_ins' => (double) $arr['disc_ins'],
			'disc_ins_percent' => (double) $arr['disc_ins_percent'],
			'claims_percent' => (double) $arr['claims_percent'],
			'equipment_percent' => (double) $arr['equipment_percent'],
			'realestate_percent' => (double) $arr['realestate_percent'],
			'commit_arm' => (double) $arr['commit_arm'],
			'commit_dist' => (double) $arr['commit_dist'],
			'commit_other' => (double) $arr['commit_other'],
			'commit_total' => (double) $arr['commit_total'],
			'principal_arm' => (double) $arr['principal_arm'],
			'principal_dist' => (double) $arr['principal_dist'],
			'principal_other' => (double) $arr['principal_other'],
			'principal' => (double) $arr['principal'],
			'arm_and_dist' => (double) $arr['arm_and_dist'],
			'collateral' => (double) $arr['collateral']
		];
	}

}