<?php namespace Acme\Transformers;

use Carbon\Carbon;
class OneloanTransformer extends Transformer{
public function transform($arr)
{
	$appDate = $arr['app_date'];
	$dueDate = $arr['due_date'];
	$diff = $dueDate->diffInDays($appDate);

	$dtToday = Carbon::now();
	$dtDOB = $arr['applicants']['farmer']['dob'];
	$age_of_farmer = $dtToday->diffInYears($dtDOB);

	$loanTypeId = (integer) $arr['loan_type_id'];
	if( $loanTypeId  == 1 || $loanTypeId == 6){
		$hasDistributor = false;
	} else {
		$hasDistributor = true;
	} // end if

	//return $arr;
	return array(
		'id'		=>	$arr['id'],
		'app_date'	=> 	$arr['app_date']->format('m/d/Y'),
		'due_date'	=>	$arr['due_date']->format('m/d/Y'),
		'loan_days' =>	$diff,
		'crop_year'	=>	$arr['crop_year'],
		'season'	=>	$arr['season'],
		'season_full' => $arr['season_full'],
		'total_acres' => $arr['total_acres'],
		'has_distributor' => (boolean) $hasDistributor,
		'crops'		=>	$arr['loancrop'],
		'cropdetails'	=>	$arr['cropdetails'],
		'entity'	=>	[
			'id'	=>	$arr['applicants']['entitytype']['id'],
			'type_id'	=>	$arr['applicants']['entitytype']['id'],
			'type'	=>	$arr['applicants']['entitytype']['entitytype'],
			'applicant_id'	=>	$arr['applicant_id'],
			'applicant'	=>	$arr['applicants']['applicant'],
			'applicant_grade' => $arr['applicants']['grade'],
			'applicant_ssn'	=>	$arr['applicants']['ssn'],
			'applicant_email'	=>	$arr['applicants']['email'],
			'applicant_dob'		=>	$arr['applicants']['dob'],
			'applicant_address'	=>	$arr['applicants']['address'],
			'applicant_city'	=>	$arr['applicants']['city'],
			'applicant_state_id'	=>	$arr['applicants']['state']['id'],
			'applicant_state_abr'	=>	$arr['applicants']['state']['abr'],
			'applicant_state'	=>	$arr['applicants']['state']['state'],
			'applicant_zip'	=>	$arr['applicants']['zip'],
			'applicant_phone'	=>	$arr['applicants']['phone'],
			'applicant_spouse'	=>	$arr['applicants']['spouse'],
			'applicant_spouse_ssn'	=>	$arr['applicants']['spouse_ssn'],
			'applicant_spouse_phone'	=>	$arr['applicants']['spouse_phone'],
			'applicant_spouse_email'	=>	$arr['applicants']['spouse_email'],
			'principals'	=>	[],
		],
		'farms'		=>	$arr['farm'],
		'farmer'	=>	[
			'farmer_id'	=>	$arr['applicants']['farmer']['id'],
			'farmer'	=>	$arr['applicants']['farmer']['farmer'],
			'ssn'		=>	$arr['applicants']['farmer']['ssn'],
			'address'	=>	$arr['applicants']['farmer']['address'],
			'city'		=>	$arr['applicants']['farmer']['city'],
			'state_id'	=>	$arr['applicants']['farmer']['state']['id'],
			'state'	=>	$arr['applicants']['farmer']['state']['state'],
			'state_abr'	=>	$arr['applicants']['farmer']['state']['abr'],
			'zip'		=>	$arr['applicants']['farmer']['zip'],
			'email'		=>	$arr['applicants']['farmer']['email'],
			'phone'		=>	$arr['applicants']['farmer']['phone'],
			'dob'		=>	date('m/d/YYYY', strtotime($arr['applicants']['farmer']['dob'])),
			'age' => $age_of_farmer,
			'farm_exp'	=>	$arr['applicants']['farmer']['farm_exp'],
		],
		'financials'	=>	[
			'total_acres' =>	(double) $arr['loanfinancial']['total_acres'],
			'guaranty' =>	(double) $arr['loanfinancial']['guaranty'],
			'prod' =>	(double) $arr['loanfinancial']['prod'],
			'adj_prod' =>	(double) $arr['loanfinancial']['adj_prod'],
			'disc_prod' =>	(double) $arr['loanfinancial']['disc_prod'],
			'disc_adj_prod' =>	(double) $arr['loanfinancial']['disc_adj_prod'],
			'ins_disc_prod' =>	(double) $arr['loanfinancial']['ins_disc_prod'],
			'disc_ins' =>	(double) $arr['loanfinancial']['disc_ins'],
			'commit_arm' => (double) $arr['loanfinancial']['commit_arm'],
			'commit_dist' => (double) $arr['loanfinancial']['commit_dist'],
			'commit_other' => (double) $arr['loanfinancial']['commit_other'],
			'commit_total' => (double) $arr['loanfinancial']['commit_total'],
			'fee_processing' => (double) $arr['loanfinancial']['fee_processing'],
			'proc_fee' => (double) $arr['loanfinancial']['proc_fee'],
			'proc_fee_arm_only' => (double) $arr['loanfinancial']['proc_fee_arm_only'],
			'fee_processing_onTotal' => (boolean) $arr['loanfinancial']['fee_processing_onTotal'],
			'fee_service' => (double) $arr['loanfinancial']['fee_service'],
			'srvc_fee' => (double) $arr['loanfinancial']['srvc_fee'],
			'srvc_fee_arm_only' => (double) $arr['loanfinancial']['srvc_fee_arm_only'],
			'fee_service_onTotal' => (boolean) $arr['loanfinancial']['fee_service_onTotal'],
			'total_fsa_payment' => (double) $arr['loanfinancial']['total_fsa_payment'],
			'total_claims' => (double) $arr['loanfinancial']['total_claims'],
			'principal_arm' => (double) $arr['loanfinancial']['principal_arm'],
			'principal_dist' => (double) $arr['loanfinancial']['principal_dist'],
			'principal_other' => (double) $arr['loanfinancial']['principal_other'],
			'principal' => (double) $arr['loanfinancial']['principal'],
			'int_percent_arm' =>	(double) $arr['loanfinancial']['int_percent_arm'],
			'int_arm' =>	(double) $arr['loanfinancial']['int_arm'],
			'int_percent_dist' =>	(double) $arr['loanfinancial']['int_percent_dist'],
			'int_dist' =>	(double) $arr['loanfinancial']['int_dist'],
			'int_percent_other' => (double) $arr['loanfinancial']['int_percent_other'],
			'int_other' => (double) $arr['loanfinancial']['int_other'],
			'interest' => (double) $arr['loanfinancial']['interest'],
			'total_revenue' => (double) $arr['loanfinancial']['total_revenue'],
			'arm_and_dist' => (double) $arr['loanfinancial']['arm_and_dist'],
			'collateral' => (double) $arr['loanfinancial']['collateral'],
			'total_balance' => (double) $arr['loanfinancial']['total_balance'],
			'remaining_balance' => (double) $arr['loanfinancial']['remaining_balance'],
			'balance_paid' => (double) $arr['loanfinancial']['balance_paid'],
			'cash_flow' => (double) $arr['loanfinancial']['cash_flow'],
			'risk' => (double) $arr['loanfinancial']['risk'],
			'year_1_revenue' => (double) $arr['loanfinancial']['year_1_revenue'],
			'year_1_expenses' => (double) $arr['loanfinancial']['year_1_expenses'],
			'year_2_revenue' => (double) $arr['loanfinancial']['year_2_revenue'],
			'year_2_expenses' => (double) $arr['loanfinancial']['year_2_expenses'],
			'year_3_revenue' => (double) $arr['loanfinancial']['year_3_revenue'],
			'year_3_expenses' => (double) $arr['loanfinancial']['year_3_expenses'],
			'current_assets' => (double) $arr['loanfinancial']['current_assets'],
			'current_asset_factor' => (double) $arr['loanfinancial']['current_asset_factor'],
			'current_asset_liability' => (double) $arr['loanfinancial']['current_asset_liability'],
			'intermediate_assets' => (double) $arr['loanfinancial']['intermediate_assets'],
			'intermediate_asset_factor' => (double) $arr['loanfinancial']['intermediate_asset_factor'],
			'intermediate_asset_liability' => (double) $arr['loanfinancial']['intermediate_asset_liability'],
			'fixed_assets' => (double) $arr['loanfinancial']['fixed_assets'],
			'fixed_asset_factor' => (double) $arr['loanfinancial']['fixed_asset_factor'],
			'fixed_asset_liability' => (double) $arr['loanfinancial']['fixed_asset_liability']
		],
		'funduses'	=>	$arr['funduses'],
		'indicator'	=>	[
			'addendum' => (boolean) $arr['addendum'],
			'bankruptcy_history' =>	(boolean) $arr['bankruptcy_history'],
			'required_3party' => (boolean) $arr['required_3party'],
			'added_land_done' => (boolean) $arr['added_land_done'],
			'controlled_disbursement' => (boolean) $arr['controlled_disbursement'],
			'attachments' => (boolean) $arr['attachments'],
			'comments' => (boolean) $arr['comments'],
		],
		'insurance'	=>	[
			'ins_agent'	=>	$arr['ins_agent'],
			'ins_agent_locale' => $arr['ins_agent_locale'],
			'ins_agent_phone' => $arr['ins_agent_phone']
		],
		'loan_type'	=>	[
			'type_id' => $arr['loan_type_id'],
			'type' => $arr['loantype']['loantype'],
			'has_addendum' => (boolean) $arr['has_addendum'],
			'is_addendum' => (boolean) $arr['is_addendum'],
			'is_reconciliation' => (boolean) $arr['is_reconciliation'],
			'is_cross_collateralized' => (boolean) $arr['is_cross_collateralized']
		],
		'location'	=>	[
			'loc_id' => $arr['loc_id'],
			'loc_abr' => $arr['location']['loc_abr'],
			'region_id'	=> $arr['region_id'],
			'region' =>	$arr['regions']['region'],
		],
		'pending' => [
			'is_stale' => (boolean) $arr['is_stale'],
			'need_vote' => (boolean) $arr['need_vote'],
			'has_comment' => (boolean) $arr['has_comment'],
		],
		'progress'	=>	[
			'its_list' => (integer) $arr['its_list'],
			'fsa_compliant' => (integer) $arr['fsa_compliant'],
			'has_liens' => (integer) $arr['has_liens'],
			'valid_leases' => (integer) $arr['valid_leases'],
			'bankruptcy_order' => (integer) $arr['bankruptcy_order'],
			'third_party_credit' =>	(integer) $arr['third_party_credit'],
			'recommended' => (integer) $arr['recommended'],
			'arm_approved' => (integer) $arr['arm_approved'],
			'dist_approved' => (integer) $arr['dist_approved'],
			'loan_closed' => (integer) $arr['loan_closed'],
			'loan_closed_date' => $arr['loan_closed_date'],
			'arm_balance' => $arr['arm_balance'],
			'added_land_verified' => (integer) $arr['added_land_verified'],
			'arm_ucc' => (integer) $arr['arm_ucc'],
			'dist_ucc' => (integer) $arr['dist_ucc'],
			'aoi_received' => (integer) $arr['aoi_received'],
			'ccc_received' => (integer) $arr['ccc_received'],
			'rebate_assignment' => (integer) $arr['rebate_assignment'],
			'limit_warning' => (integer) $arr['limit_warning'],
			'crop_inspection' => (integer) $arr['crop_inspection'],
			'reconcilliation' => (integer) $arr['reconcilliation'],
			'account_classification' => (integer) $arr['account_classification'],
			'paid' =>	(integer) $arr['paid'],
			'loan_paid' =>	(integer) $arr['loan_paid'],
			'perfected_attachments' =>	(integer) $arr['perfected_attachments'],
			'grade' =>	$arr['grade']
		],
		'quests' => [
			'amount_requested' => (double) $arr['loanquestions'][0]->amount_requested,
			'plant_own'	=>	(boolean) $arr['loanquestions'][0]->plant_own,
			'plant_own_details'	=>	$arr['loanquestions'][0]->plant_own_details,
			'harvest_own'	=>	(boolean) $arr['loanquestions'][0]->harvest_own,
			'harvest_own_details'	=>	$arr['loanquestions'][0]->harvest_own_details,
			'equip_obligations'	=>	(boolean) $arr['loanquestions'][0]->equip_obligations,
			'equip_obligations_details'	=>	$arr['loanquestions'][0]->equip_obligations_details,
			'other_cash'	=>	(boolean) $arr['loanquestions'][0]->other_cash,
			'other_cash_details'	=>	$arr['loanquestions'][0]->other_cash_details,
			'fsa_good'	=>	(boolean) $arr['loanquestions'][0]->fsa_good,
			'fsa_good_details'	=>	$arr['loanquestions'][0]->fsa_good_details,
			'insInPlace'	=>	(boolean) $arr['loanquestions'][0]->insInPlace,
			'insInPlace_details'	=>	$arr['loanquestions'][0]->insInPlace_details,
			'fci_good'	=>	(boolean) $arr['loanquestions'][0]->fci_good,
			'fci_good_details'	=>	$arr['loanquestions'][0]->fci_good_details,
			'premiums_past'	=>	(boolean) $arr['loanquestions'][0]->premiums_past,
			'premiums_details'	=>	$arr['loanquestions'][0]->premiums_details,
			'legal_defendant'	=>	(boolean) $arr['loanquestions'][0]->legal_defendant,
			'defendant_details'	=>	$arr['loanquestions'][0]->defendant_details,
			'judgements'	=>	(boolean) $arr['loanquestions'][0]->judgements,
			'judgement_details'	=>	$arr['loanquestions'][0]->judgement_details,
			'bankruptcy'	=>	(boolean) $arr['loanquestions'][0]->bankruptcy,
			'bankruptcy_details' =>	$arr['loanquestions'][0]->bankruptcy_details,
			'bankruptcy_order' => (boolean) $arr['loanquestions'][0]->bankruptch_order,
			'liens'	=>	(boolean) $arr['loanquestions'][0]->liens,
			'liens_details'	=>	$arr['loanquestions'][0]->liens_details,
			'fsa_direct_pay'	=>	(boolean) $arr['loanquestions'][0]->fsa_direct_pay,
			'fsa_direct_pay_details'	=>	$arr['loanquestions'][0]->fsa_direct_pay_details,
			'future_liabilities'	=>	(boolean) $arr['loanquestions'][0]->future_liabilities,
			'credit_3p_available'	=>	(boolean) $arr['loanquestions'][0]->credit_3p_available,
			'credit_3p_details'	=>	$arr['loanquestions'][0]->credit_3p_details,
			'income_percent'	=>	(double) $arr['loanquestions'][0]->income_percent,
			'income_distribution_details' =>	$arr['loanquestions'][0]->income_distribution_details,
			'distributor'	=>	$arr['loanquestions'][0]->distributor,
			'pesticide_number'	=>	$arr['loanquestions'][0]->pesticide_number,
			'credit_score'	=>	$arr['loanquestions'][0]->credit_score,
			'cpa_financials' =>	(boolean) $arr['loanquestions'][0]->cpa_financials,
			'affiliated_entities'	=>	$arr['loanquestions'][0]->affiliated_entities,
			'farm_supplier_creditors'	=>	$arr['loanquestions'][0]->farm_supplier_creditors
		],
		'staff' =>	[
			'user_id' => $arr['user_id'],
			'analyst_id' => $arr['user']['id'],
			'analyst' => $arr['user']['abr'],
			'officer' => $arr['user']['username'],
			'email' => $arr['user']['email'],
			'manager' => $arr['user']['manager_id']
		],
		'status' =>	[
			'id' =>	$arr['status_id'],
			'status' =>	$arr['loanstatus']['status'],
			'iconClass' => $arr['loanstatus']['iconClass'],
			'iconColor' => $arr['loanstatus']['iconColor']
		],
		'comments'	=>	$arr['comment'],
		'committee'	=>	$arr['committee'],
		'stakeholders' => $arr['stakeholders'],
		'documents'	=>	$arr['prerequisites'],
		'loanConditions' => $arr['loanconditions'],
		'systemics' => $arr['systemics']
	);
}

}