<?php namespace Acme\Transformers;


class UserTransformer extends Transformer
{

  public function transform($arr)
  {
    //return $arr;
      $pender = 0;
      $manager = 0;
      $reporter = 0;

      foreach($arr['notifications'] as $notifs){
          if($notifs['notification_type'] == 'vote' || $notifs['notification_type'] == 'comment'){
              if($notifs['status'] == 'pending') {
                  $pender++;
              }
          }
          if($notifs['notification_type'] == 'office'){
              if($notifs['status'] == 'pending') {
                  $manager++;
              }
          }
          if($notifs['notification_type'] == 'report'){
              if($notifs['status'] == 'pending') {
                  $reporter++;
              }
          }
      }

    return [
        'id' => $arr['id'],
        'email' => $arr['email'],
        'outlook' => $arr['outlook'],
        'username' => $arr['username'],
        'nick' => $arr['nick'],
        'phone' => $arr['phone'],
        'region_id' => $arr['region_id'],
        'region' => $arr['region']['region'],
        'loc_id' => $arr['loc_id'],
        'loc_abr' => $arr['location']['loc_abr'],
        'location' => $arr['location']['location'],
        'manager_id' => $arr['manager_id'],
        'manager' => $arr['manager']['username'],
        'manager_email' => $arr['manager']['email'],
        'full_sidebar' => (boolean)$arr['full_sidebar'],
        'comms_email' => (boolean)$arr['comms_email'],
        'comms_sms' => (boolean)$arr['comms_sms'],
        'comms_outlook' => (boolean)$arr['comms_outlook'],
        'comms_online' => (boolean)$arr['comms_online'],
        'closer_id' => $arr['closer_id'],
        'closer' => $arr['closer']['username'],
        'closer_email' => $arr['closer']['email'],
        'is_admin' => (boolean) $arr['is_admin'],
        'is_approver' => (boolean) $arr['is_approver'],
        'is_manager' => (boolean) $arr['is_manager'],
        'role_id' => $arr['role_id'],
        'role' => $arr['role']['role'],
        'role_abr' => $arr['role']['abr'],
        'homepage' => $arr['profile']['homepage'],
        'commentopts' => [
            'cbCommentLenda' => (boolean) $arr['profile']['cbCommentLenda'],
            'cbCommentCommittee' => (boolean) $arr['profile']['cbCommentCommittee'],
            'cbCommentAnalyst' => (boolean) $arr['profile']['cbCommentAnalyst'],
            'cbCommentAccount' => (boolean) $arr['profile']['cbCommentAccount'],
            'cbStatusInProgress' => (boolean) $arr['profile']['cbStatusInProgress'],
            'cbStatusRecommended' => (boolean) $arr['profile']['cbStatusRecommended'],
            'cbStatusWithdrawn' => (boolean) $arr['profile']['cbStatusWithdrawn'],
            'cbStatusApproved' => (boolean) $arr['profile']['cbStatusApproved'],
            'cbStatusDenied' => (boolean) $arr['profile']['cbStatusDenied'],
            'cbStatusPaid' => (boolean) $arr['profile']['cbStatusPaid']
        ],
        'notifications' => $arr['notifications'],
        'notificator' => [
            'count' => $pender + $manager + $reporter,
            'pending_actions' => $pender,
            'management_required' => $manager,
            'review_reports' => $reporter
        ],
        'rptfltr' => [
            'report_region' => (boolean) $arr['reportoptions']['report_region'],
            'report_season' => (boolean) $arr['reportoptions']['report_season'],
            'report_distributor' => (boolean) $arr['reportoptions']['report_distributor'],
            'report_agency' => (boolean) $arr['reportoptions']['report_agency'],
            'report_close_date' => (boolean) $arr['reportoptions']['report_close_date'],
            'report_commit_total' => (boolean) $arr['reportoptions']['report_commit_total'],
            'report_commit_arm' => (boolean) $arr['reportoptions']['report_commit_arm'],
            'report_commit_distributor' => (boolean) $arr['reportoptions']['report_commit_distributor'],
            'report_commit_other' => (boolean) $arr['reportoptions']['report_commit_other'],
            'report_fee_percentage' => (boolean) $arr['reportoptions']['report_fee_percentage'],
            'report_fee_total' => (boolean) $arr['reportoptions']['report_fee_total'],
            'report_rate_arm' => (boolean) $arr['reportoptions']['report_rate_arm'],
            'report_rate_dist' => (boolean) $arr['reportoptions']['report_rate_dist'],
            'report_balance_due' => (boolean) $arr['reportoptions']['report_balance_due'],
            'report_acres_total' => (boolean) $arr['reportoptions']['report_acres_total'],
            'report_acres_corn' => (boolean) $arr['reportoptions']['report_acres_corn'],
            'report_acres_soybeans' => (boolean) $arr['reportoptions']['report_acres_soybeans'],
            'report_acres_sorghum' => (boolean) $arr['reportoptions']['report_acres_sorghum'],
            'report_acres_wheat' => (boolean) $arr['reportoptions']['report_acres_wheat'],
            'report_acres_cotton' => (boolean) $arr['reportoptions']['report_acres_cotton'],
            'report_acres_rice' => (boolean) $arr['reportoptions']['report_acres_rice'],
            'report_acres_peanuts' => (boolean) $arr['reportoptions']['report_acres_peanuts'],
            'report_acres_sugar_cane' => (boolean) $arr['reportoptions']['report_acres_sugar_cane'],
            'report_icon_addendum' => (boolean) $arr['reportoptions']['report_icon_addendum'],
            'report_icon_cross' => (boolean) $arr['reportoptions']['report_icon_cross'],
            'report_icon_bankruptcy' => (boolean) $arr['reportoptions']['report_icon_bankruptcy'],
            'report_icon_3pcredit' => (boolean) $arr['reportoptions']['report_icon_3pcredit'],
            'report_icon_addedland' => (boolean) $arr['reportoptions']['report_icon_addedland'],
            'report_icon_disbursement' => (boolean) $arr['reportoptions']['report_icon_disbursement'],
            'report_icon_attachments' => (boolean) $arr['reportoptions']['report_icon_attachments']
        ],
        'rptopts' => [
            'report_region' => (boolean) $arr['reportoptions']['report_region'],
            'report_season' => (boolean) $arr['reportoptions']['report_season'],
            'report_distributor' => (boolean) $arr['reportoptions']['report_distributor'],
            'report_agency' => (boolean) $arr['reportoptions']['report_agency'],
            'report_close_date' => (boolean) $arr['reportoptions']['report_close_date'],
            'report_commit_total' => (boolean) $arr['reportoptions']['report_commit_total'],
            'report_commit_arm' => (boolean) $arr['reportoptions']['report_commit_arm'],
            'report_commit_distributor' => (boolean) $arr['reportoptions']['report_commit_distributor'],
            'report_commit_other' => (boolean) $arr['reportoptions']['report_commit_other'],
            'report_fee_percentage' => (boolean) $arr['reportoptions']['report_fee_percentage'],
            'report_fee_total' => (boolean) $arr['reportoptions']['report_fee_total'],
            'report_rate_arm' => (boolean) $arr['reportoptions']['report_rate_arm'],
            'report_rate_dist' => (boolean) $arr['reportoptions']['report_rate_dist'],
            'report_balance_due' => (boolean) $arr['reportoptions']['report_balance_due'],
            'report_acres_total' => (boolean) $arr['reportoptions']['report_acres_total'],
            'report_acres_corn' => (boolean) $arr['reportoptions']['report_acres_corn'],
            'report_acres_soybeans' => (boolean) $arr['reportoptions']['report_acres_soybeans'],
            'report_acres_sorghum' => (boolean) $arr['reportoptions']['report_acres_sorghum'],
            'report_acres_wheat' => (boolean) $arr['reportoptions']['report_acres_wheat'],
            'report_acres_cotton' => (boolean) $arr['reportoptions']['report_acres_cotton'],
            'report_acres_rice' => (boolean) $arr['reportoptions']['report_acres_rice'],
            'report_acres_peanuts' => (boolean) $arr['reportoptions']['report_acres_peanuts'],
            'report_acres_sugar_cane' => (boolean) $arr['reportoptions']['report_acres_sugar_cane'],
            'report_icon_addendum' => (boolean) $arr['reportoptions']['report_icon_addendum'],
            'report_icon_cross' => (boolean) $arr['reportoptions']['report_icon_cross'],
            'report_icon_bankruptcy' => (boolean) $arr['reportoptions']['report_icon_bankruptcy'],
            'report_icon_3pcredit' => (boolean) $arr['reportoptions']['report_icon_3pcredit'],
            'report_icon_addedland' => (boolean) $arr['reportoptions']['report_icon_addedland'],
            'report_icon_disbursement' => (boolean) $arr['reportoptions']['report_icon_disbursement'],
            'report_icon_attachments' => (boolean) $arr['reportoptions']['report_icon_attachments']
        ],
        'viewfltr' => [
            'vfRegions' => $arr['viewfilters']['vfRegions'],
            'vfFarmers' => $arr['viewfilters']['vfFarmers'],
            'vfAnalysts' => $arr['viewfilters']['vfAnalysts'],
            'vfCropYears' => $arr['viewfilters']['vfCropYears'],
            'vfSeasons' => $arr['viewfilters']['vfSeasons'],
            'vfLoanTypes' => $arr['viewfilters']['vfLoanTypes'],
            'vfDistributors' => $arr['viewfilters']['vfDistributors'],
            'vfAgencies' => $arr['viewfilters']['vfAgencies'],
            'vfAddendums' => (boolean) $arr['viewfilters']['vfAddendums'],
            'vfComments' => (boolean) $arr['viewfilters']['vfComments'],
            'vfBankruptcy' => (boolean) $arr['viewfilters']['vfBankruptcy'],
            'vfThirdParty' => (boolean) $arr['viewfilters']['vfThirdParty'],
            'vfAddedLand' => (boolean) $arr['viewfilters']['vfAddedLand'],
            'vfDisbursements' => (boolean) $arr['viewfilters']['vfDisbursements'],
            'vfAttachments' => (boolean) $arr['viewfilters']['vfAttachments'],
            'vfLimitClose' => (boolean) $arr['viewfilters']['vfLimitClose'],
            'vfLimitExceeded' => (boolean) $arr['viewfilters']['vfLimitExceeded'],
            'vfAppDate' => $arr['viewfilters']['vfAppDate'],
            'vfAppDateFilter' => $arr['viewfilters']['vfAppDateFilter'],
            'vfCloseDate' => $arr['viewfilters']['vfCloseDate'],
            'vfCloseDateFilter' => $arr['viewfilters']['vfCloseDateFilter'],
            'vfDueDate' => $arr['viewfilters']['vfDueDate'],
            'vfDueDateFilter' => $arr['viewfilters']['vfDueDateFilter'],
            'vfCommitTotal' => $arr['viewfilters']['vfCommitTotal'],
            'vfCommitArm' => $arr['viewfilters']['vfCommitArm'],
            'vfCommitDist' => $arr['viewfilters']['vfCommitDist'],
            'vfCommitOther' => $arr['viewfilters']['vfCommitOther'],
            'vfFee' => $arr['viewfilters']['vfFee'],
            'vfRateArm' => $arr['viewfilters']['vfRateArm'],
            'vfRateDist' => $arr['viewfilters']['vfRateDist'],
            'vfRateOther' => $arr['viewfilters']['vfRateOther'],
            'vfAcresTotal' => $arr['viewfilters']['vfAcresTotal'],
            'vfAcresBeansFAC' => $arr['viewfilters']['vfAcresBeansFAC'],
            'vfAcresCorn' => $arr['viewfilters']['vfAcresCorn'],
            'vfAcresBeans' => $arr['viewfilters']['vfAcresBeans'],
            'vfAcresSorghum' => $arr['viewfilters']['vfAcresSorghum'],
            'vfAcresWheat' => $arr['viewfilters']['vfAcresWheat'],
            'vfAcresCotton' => $arr['viewfilters']['vfAcresCotton'],
            'vfAcresRice' => $arr['viewfilters']['vfAcresRice'],
            'vfAcresPeanuts' => $arr['viewfilters']['vfAcresPeanuts'],
            'vfAcresCane' => $arr['viewfilters']['vfAcresCane'],
            'vfAcresOther' => $arr['viewfilters']['vfAcresOther'],
            'vfStatusApproved' => (boolean)$arr['viewfilters']['vfStatusApproved'],
            'vfStatusDenied' => (boolean)$arr['viewfilters']['vfStatusDenied'],
            'vfStatusInProgress' => (boolean)$arr['viewfilters']['vfStatusInProgress'],
            'vfStatusPaid' => (boolean)$arr['viewfilters']['vfStatusPaid'],
            'vfStatusRecommended' => (boolean)$arr['viewfilters']['vfStatusRecommended'],
            'vfStatusWithdrawn' => (boolean)$arr['viewfilters']['vfStatusWithdrawn']
        ],
        'viewopts' => [
            'voDueDate' => (boolean) $arr['viewoptions']['voDueDate'],
            'voRegion' => (boolean) $arr['viewoptions']['voRegion'],
            'voSeason' => (boolean) $arr['viewoptions']['voSeason'],
            'voDistributor' => (boolean) $arr['viewoptions']['voDistributor'],
            'voAgency' => (boolean) $arr['viewoptions']['voAgency'],
            'voCloseDate' => (boolean) $arr['viewoptions']['voCloseDate'],
            'voCommitTotal' => (boolean) $arr['viewoptions']['voCommitTotal'],
            'voCommitArm' => (boolean) $arr['viewoptions']['voCommitArm'],
            'voCommitDistributor' => (boolean) $arr['viewoptions']['voCommitDistributor'],
            'voCommitOther' => (boolean) $arr['viewoptions']['voCommitOther'],
            'voFeePercentage' => (boolean) $arr['viewoptions']['voFeePercentage'],
            'voFeeTotal' => (boolean) $arr['viewoptions']['voFeeTotal'],
            'voRateArm' => (boolean) $arr['viewoptions']['voRateArm'],
            'voRateDist' => (boolean) $arr['viewoptions']['voRateDist'],
            'voBalanceDue' => (boolean) $arr['viewoptions']['voBalanceDue'],
            'voAcresTotal' => (boolean) $arr['viewoptions']['voAcresTotal'],
            'voAcresCorn' => (boolean) $arr['viewoptions']['voAcresCorn'],
            'voAcresSoybeans' => (boolean) $arr['viewoptions']['voAcresSoybeans'],
            'voAcresBeansFAC' => (boolean) $arr['viewoptions']['voAcresBeansFAC'],
            'voAcresSorghum' => (boolean) $arr['viewoptions']['voAcresSorghum'],
            'voAcresWheat' => (boolean) $arr['viewoptions']['voAcresWheat'],
            'voAcresCotton' => (boolean) $arr['viewoptions']['voAcresCotton'],
            'voAcresRice' => (boolean) $arr['viewoptions']['voAcresRice'],
            'voAcresPeanuts' => (boolean) $arr['viewoptions']['voAcresPeanuts'],
            'voAcresSugarcane' => (boolean) $arr['viewoptions']['voAcresSugarcane'],
            'voAcresOther' => (boolean) $arr['viewoptions']['voAcresOther'],
            'voIconAddendum' => (boolean) $arr['viewoptions']['voIconAddendum'],
            'voIconCross' => (boolean) $arr['viewoptions']['voIconCross'],
            'voIconBankruptcy' => (boolean) $arr['viewoptions']['voIconBankruptcy'],
            'voIcon3pcredit' => (boolean) $arr['viewoptions']['voIcon3pcredit'],
            'voIconAddedland' => (boolean) $arr['viewoptions']['voIconAddedland'],
            'voIconDisbursement' => (boolean) $arr['viewoptions']['voIconDisbursement'],
            'voIconAttachments' => (boolean) $arr['viewoptions']['voIconAttachments']
      ],
        'optimopts' => [
            'rent_per_acre_ARM' => (boolean)$arr['optimizeroptions']['rent_per_acre_ARM'],
            'rent_per_acre_dist' => (boolean)$arr['optimizeroptions']['rent_per_acre_dist'],
            'rent_per_acre_other' => (boolean)$arr['optimizeroptions']['rent_per_acre_other'],
            'fsa_per_acre' => (boolean)$arr['optimizeroptions']['fsa_per_acre_other'],
            'ins_share' => (boolean)$arr['optimizeroptions']['ins_share'],
            'ins_price' => (boolean)$arr['optimizeroptions']['ins_price'],
            'ins_level' => (boolean)$arr['optimizeroptions']['ins_level'],
            'ins_guarantee' => (boolean)$arr['optimizeroptions']['ins_guarantee'],
            'ins_premium' => (boolean)$arr['optimizeroptions']['ins_premium'],
            'ins_value' => (boolean)$arr['optimizeroptions']['ins_value'],
            'ins_type' => (boolean)$arr['optimizeroptions']['ins_type'],
            'sco_max' => (boolean)$arr['optimizeroptions']['sco_max'],
            'prod_yield' => (boolean)$arr['optimizeroptions']['prod_yield'],
            'prod_share' => (boolean)$arr['optimizeroptions']['prod_share'],
            'prod_price' => (boolean)$arr['optimizeroptions']['prod_price'],
            'var_harvest' => (boolean)$arr['optimizeroptions']['var_harvest'],
            'rebate' => (boolean)$arr['optimizeroptions']['rebate'],
            'prod_rev' => (boolean)$arr['optimizeroptions']['prod_rev'],
            'prod_rev_adj' => (boolean)$arr['optimizeroptions']['prod_rev_adj'],
            'budget_ARM' => (boolean)$arr['optimizeroptions']['budget_ARM'],
            'budget_dist' => (boolean)$arr['optimizeroptions']['budget_dist'],
            'budget_other' => (boolean)$arr['optimizeroptions']['budget_other'],
            'fee_ARM' => (boolean)$arr['optimizeroptions']['fee_ARM'],
            'commit_ARM' => (boolean)$arr['optimizeroptions']['commit_ARM'],
            'commit_dist' => (boolean)$arr['optimizeroptions']['commit_dist'],
            'interest_ARM' => (boolean)$arr['optimizeroptions']['interest_ARM'],
            'interest_dist' => (boolean)$arr['optimizeroptions']['interest_dist'],
            'interest_other' => (boolean)$arr['optimizeroptions']['interest_other'],
            'percent_disc_crop' => (boolean)$arr['optimizeroptions']['percent_disc_crop'],
            'percent_disc_fsa' => (boolean)$arr['optimizeroptions']['percent_disc_fsa'],
            'percent_disc_cropins' => (boolean)$arr['optimizeroptions']['percent_disc_cropins'],
            'percent_disc_nonrp' => (boolean)$arr['optimizeroptions']['percent_disc_nonrp'],
            'percent_disc_sco' => (boolean)$arr['optimizeroptions']['percent_disc_sco'],
            'disc_crop' => (boolean)$arr['optimizeroptions']['disc_crop'],
            'disc_fsa' => (boolean)$arr['optimizeroptions']['disc_fsa'],
            'disc_insovercrop' => (boolean)$arr['optimizeroptions']['disc_insovercrop'],
            'disc_ins' => (boolean)$arr['optimizeroptions']['disc_ins'],
            'disc_sco' => (boolean)$arr['optimizeroptions']['disc_sco'],
            'disc_collateral' => (boolean)$arr['optimizeroptions']['disc_collateral']
        ]
    ];

  }
}